### PR TITLE
Unit Testing for Recommended Attractions based on User Preferred Activity Type

### PR DESCRIPTION
**Pull request by emilynairnn**
Unit Test for recommend attractions based on preferred activity type.

Test with the city = Toronto, group size = 2, start date = 2020-12-3, end date = 2020-12-5, user = emily@outlook.com.

Assert - should return 2 attractions
* note - this user has a TRAVVY account where their preferred activity type is active. This is shown in the response, as their are only two attractions that should be displayed given the above parameters, that are also considered active.

### CODE REVIEW

**Comment by lucasungaretti** [comment]
did you try for different test cases? aka different emails?

**Comment by emilynairnn** [comment]
> did you try for different test cases? aka different emails?

Thanks for the recommendation Lucas! Since it is only testing one part of the recommend function, the other test cases are tested in the same test file under "Unit Tests for Home Page".

**Review by lkdfount — COMMENTED** [review]
This looks good however I think I saw your previous PR also changed the AuthenticationController for onboarding, should we be changing or adding unit tests for that as well?

**Comment by emilynairnn** [comment]
> This looks good however I think I saw your previous PR also changed the AuthenticationController for onboarding, should we be changing or adding unit tests for that as well?

Great catch! All that was changed in the AuthenticationController file was adding the activity_id as a parameter, since it was a column added to the Users table in the database. Since all the unit testing for AuthenticationController is passing, it would mean that this functionality is also working. But now that you mention it I will create another unit test just to be sure.

**Pull request merged**
