### PR TITLE
Update the style tag to match with the other pages

### PR DESCRIPTION
**Pull request by emilynairnn**
- added different styles
- updated the button to match the other pages

### CODE REVIEW

**Comment by lkdfount** [comment]
We talked about this earlier, all the code looks good to me

**Comment by rushanniazi** [comment]
Great job with the updated style, looks good to me!

**Comment by lucasungaretti** [comment]
Isn't there a way to reference the travvy style withough copying it all in?

**Comment by rushanniazi** [comment]
> Isn't there a way to reference the travvy style withough copying it all in?

**Pull request merged**
